services:
  pgadmin:
    image: dpage/pgadmin4
    user: pgadmin
    env_file:
      - .env
    volumes:
      # IMPORTANT
      # Named volumes ensure portability across the host plaforms used to
      # create and run development containers.
      - capxmlpgadmin:/var/lib/pgadmin
    ports:
      - "127.0.0.1:8080:80"
    networks:
      ls:
  liquibase:
    image: liquibase/liquibase
    depends_on:
      capxmldb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      # IMPORTANT
      # Named volumes ensure portability across the host plaforms used to
      # create and run development containers.
      - capxmlliquibase:/capxmldb
    networks:
      ls:
    command: /bin/sh -c "lpm add postgresql && liquibase update"
  mock-api:
    image: wiremock/wiremock:latest
    ports:
      - "8081:8080"
    volumes:
      - ./docker/wiremock/mappings:/home/wiremock/mappings
    command: ["--global-response-templating", "--verbose"]
    networks:
      ls:
volumes:
  capxmlpgadmin:
    external: true
  capxmlliquibase:
    external: true